spring:
  flyway:
    enabled: false
    locations:
      - classpath:/migrations-test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: false


logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework: WARN